[package]
name = "v8js"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ext-php-rs = "0.10.0"
v8 = "0.38.1"

[lib]
crate-type = ["cdylib"]
