[package]
name = "v8js"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ext-php-rs = "0.11.1"
v8 = "0.82.0"

[lib]
crate-type = ["cdylib"]
